-- Cria a tabela de cache de traduções
CREATE TABLE IF NOT EXISTS game_translations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id BIGINT NOT NULL, -- ID original do IGDB
  language TEXT NOT NULL,  -- Ex: 'pt-BR'
  summary TEXT,            -- Descrição traduzida
  storyline TEXT,          -- Enredo traduzido
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Garante que não tenhamos duplicatas (mesmo jogo + mesma língua)
  UNIQUE(game_id, language)
);

-- Cria um índice para busca ficar instantânea
CREATE INDEX IF NOT EXISTS idx_game_translations_lookup ON game_translations(game_id, language);

-- Habilitar RLS
ALTER TABLE game_translations ENABLE ROW LEVEL SECURITY;

-- Política de leitura pública
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'game_translations' AND policyname = 'Leitura pública'
    ) THEN
        CREATE POLICY "Leitura pública" ON game_translations FOR SELECT USING (true);
    END IF;
END
$$;
